
export const REGISTER__START = "REGISTER__START";
export const REGISTER__SUCCESS = "REGISTER__SUCCESS";
export const REGISTER__FAILED = "REGISTER__FAILED";

export const LOGIN__START = "LOGIN__START";
export const LOGIN__SUCCESS = "LOGIN__SUCCESS";
export const LOGIN__FAILED = "LOGIN__FAILED";


export const SET__INIT = "SET_INIT";
export const LOGOUT__INIT = "LOGOUT_INIT";

export const CREATE__BLOG__START = "CREATE__BLOG__START";
export const CREATE__BLOG__SUCCESS = "CREATE__BLOG__SUCCESS";
export const CREATE__BLOG__FAILED = "CREATE__BLOG__FAILED";

export const FETCH__BLOGS__START = "FETCH__BLOGS__START";
export const FETCH__BLOGS__SUCCESS = "FETCH__BLOGS__SUCCESS";
export const FETCH__BLOGS__FAILED = "FETCH__BLOGS__FAILED";


export const FETCH__BLOG__START = "FETCH__BLOG__START";
export const FETCH__BLOG__SUCCESS = "FETCH__BLOG__SUCCESS";
export const FETCH__BLOG__FAILED = "FETCH__BLOG__FAILED";

export const UPDATE__BLOG__START = "UPDATE__BLOG__START";
export const UPDATE__BLOG__SUCCESS = "UPDATE__BLOG__SUCCESS";
export const UPDATE__BLOG__FAILED = "UPDATE__BLOG__FAILED";

export const DELETE__BLOG__START = "DELETE__BLOG__START"
export const DELETE__BLOG__SUCCESS = "DELETE__BLOG__SUCCESS"
export const DELETE__BLOG__FAILED = "DELETE__BLOG__FAILED"

export const CREATE__COMMENT__START = "CREATE__COMMENT__START";
export const CREATE__COMMENT__SUCCESS = "CREATE__COMMENT__SUCCESS";
export const CREATE__COMMENT__FAILED = "CREATE__COMMENT__FAILED";

export const FETCH__COMMENT__START = "FETCH__COMMENT__START";
export const FETCH__COMMENT__SUCCESS = "FETCH__COMMENT__SUCCESS";
export const FETCH__COMMENT__FAILED = "FETCH__COMMENT__FAILED";

export const FETCH__USER__START = "FETCH__USER__START";
export const FETCH__USER__SUCCESS = "FETCH__USER__SUCCESS";
export const FETCH__USER__FAILED = "FETCH__USER__FAILED";

export const UPDATE__USER__START = "UPDATE__USER__START";
export const UPDATE__USER__SUCCESS = "UPDATE__USER__SUCCESS";
export const UPDATE__USER__FAILED = "UPDATE__USER__FAILED";

export const FETCH__DETAILS__START = "FETCH__DETAILS__START"
export const FETCH__DETAILS__SUCCESS = "FETCH__DETAILS__SUCCESS"
export const FETCH__DETAILS__FAILED = "FETCH__DETAILS__FAILED"


export const CHANGE__EDIT__STATE = "CHANGE__EDIT__STATE";

export const SET__BLOG__INIT = "SET__BLOG__INIT"

